version: '3.7'

services:

  app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000" # Map port 3000 of the host to port 3000 of the container
    environment:
      - MONGODB_URI=mongodb://mongo:27017/librerie # Connection string for MongoDB
    depends_on:
      - mongo # Ensures MongoDB starts before the app
    volumes:
      - .:/usr/src/app # Mount the current directory to the container
    networks:
      - app-network # Connect to the custom network 'app-network'

  mongo:
    image: mongo:latest
    container_name: my-mongo-db
    ports:
      - "27018:27017" # Expose MongoDB on port 27018 on the host (MongoDB defaults to 27017)
    volumes:
      - ./data:/data/db # Persist MongoDB data on the host in the './data' folder
    networks:
      - app-network # Connect to the custom network 'app-network'

networks:
  app-network:
    driver: bridge # Use the bridge driver for network isolation
